[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F411CEUx with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32F411CEUx"

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
